### ISSUE TITLE
keys with bigger RSA headers fail

### ISSUE THREAD

**Issue by denuno** [craigwblake/redline#62]
I'm not sure if it's how I generated my keys (did the standard gpg keygen using 4096), or what, but I was getting this error when I tried to sign:

```
java.lang.RuntimeException: Error writing pending entry '268'.
    at org.redline_rpm.header.AbstractHeader.writePending(AbstractHeader.java:182)
aused by: java.nio.BufferOverflowException
    at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189)
```

With a bit of debugging it appears that the default SIGNATURE_SIZE size of 287 wasn't enough for the apparent 543 length ones in these keys?  Bumping the size up to 543 fixes the issue.

**Comment by theoweiss** [comment]
Is this issue still open? It would be great to have a fix for this.
Unfortunately I myself have no knowledge about rpm package structure but may be could get some inspiration from here: https://github.com/eclipse/packagedrone/blob/master/bundles/org.eclipse.packagedrone.utils.rpm/src/org/eclipse/packagedrone/utils/rpm/signature/RsaHeaderSignatureProcessor.java

**Comment by BClark09** [comment]
Any chance that @denuno's latest version of the fork could make it into the main branch? Or at least have a method of supplying an arbitrary signature size so that the ospackage-plugin (and then those using it) can use one for a key of known size?

**Comment by pdeva** [comment]
this issue is still present and prevents signing of rpms...
