### ISSUE TITLE
Can't run Scanner without adding slf4j lib to classpath

### ISSUE THREAD

**Issue by pausebreak** [craigwblake/redline#72]
Your docs say:
```
 java -cp redline.jar org.redline_rpm.Scanner test.rpm
```

But the result with 1.2.1 is:

java -cp redline-1.2.1.jar org.redline_rpm.Scanner rpm.rpm

Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.redline_rpm.Scanner.<clinit>(Scanner.java:33)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by craigwblake** [comment]
Fixed the usage page on the site to use the correct JAR with dependencies:
